spring.application.name=payment-service

server.port=${SERVER_PORT}

# =========================
# DATABASE
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW}

# =========================
# HIKARI CONNECTION POOL
# =========================

spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}

spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}

spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}

spring.datasource.hikari.idle-timeout=${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT}

spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}

# =========================
# KAFKA
# =========================

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =========================
# FEIGN + OKHTTP
# =========================

spring.cloud.openfeign.okhttp.enabled=true

spring.cloud.openfeign.httpclient.hc5.enabled=false

spring.cloud.openfeign.client.config.default.connectTimeout=3000

spring.cloud.openfeign.client.config.default.readTimeout=5000

spring.cloud.openfeign.client.config.default.loggerLevel=basic

# =========================
# TOMCAT OPTIMIZATION
# =========================

server.tomcat.threads.max=200

server.tomcat.accept-count=100

server.tomcat.max-connections=8192

server.tomcat.connection-timeout=2000

server.tomcat.keep-alive-timeout=15000

server.tomcat.max-keep-alive-requests=100

# =========================
# RESPONSE COMPRESSION
# =========================

server.compression.enabled=true

server.compression.mime-types=application/json

server.compression.min-response-size=1024

# =========================
# JWT
# =========================

jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION}

# Virtual Threads
spring.threads.virtual.enabled=true

# Kafka Producer Serializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false
